import type {
  AnswerReviewStatus,
  QuestionInput,
  ResultItem,
  RunStatus
} from "./types";

export type StartRunResponse = {
  runId: string;
  results?: ResultItem[];
};

export type GetRunStatusResponse = {
  status: RunStatus;
  results?: ResultItem[];
  error?: string;
};

// Prefer relative /api calls (works with Vite proxy in dev, same-origin in prod).
// Override with VITE_BACKEND_URL when deploying backend separately.
const API_BASE_URL = ((import.meta as any).env?.VITE_BACKEND_URL ?? "") as string;

function apiUrl(path: string): string {
  const base = (API_BASE_URL || "").trim().replace(/\/+$/, "");
  const p = path.startsWith("/") ? path : `/${path}`;
  return base ? `${base}${p}` : p;
}

const START_RUN_TIMEOUT_MS = 15000;

export type RAGBuildResponse = {
  built_from: string;
  documents_indexed: number;
  chunks_indexed: number;
};

type BackendRunResultItem = {
  question_id: string;
  question_text: string;
  answer: string;
  status?: AnswerReviewStatus;
  review_notes?: string;
  reviewed_by?: string;
  reviewed_at?: string;
  citations: {
    document: string;
    section: string;
    snippet: string;
    [key: string]: unknown;
  }[];
};

type BackendStartRunResponse = {
  runId: string;
  results: BackendRunResultItem[];
};

export async function startRun(
  questions: QuestionInput[]
): Promise<StartRunResponse> {
  const controller = new AbortController();
  const timeout = window.setTimeout(
    () => controller.abort(),
    START_RUN_TIMEOUT_MS
  );

  try {
    const response = await fetch(apiUrl("/api/run"), {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ questions }),
      signal: controller.signal
    });

    if (!response.ok) {
      const message = await safeReadErrorMessage(response);
      throw new Error(
        message ?? `Failed to start run (status ${response.status}).`
      );
    }

    const data = (await response.json()) as BackendStartRunResponse;

    const results: ResultItem[] = (data.results ?? []).map((item) => ({
      questionId: item.question_id,
      questionText: item.question_text,
      answer: item.answer,
      status: item.status ?? "draft",
      review_notes: item.review_notes,
      reviewed_by: item.reviewed_by,
      reviewed_at: item.reviewed_at,
      citations: item.citations.map((c) => ({
        document: c.document,
        section: c.section,
        snippet: c.snippet
      }))
    }));

    return { runId: data.runId, results };
  } catch (err) {
    // Demo fallback: if backend isn't running/reachable, still complete the flow.
    const isAbort =
      err instanceof DOMException && err.name === "AbortError";

    const runId = `demo-run-${Date.now()}`;
    const results: ResultItem[] = questions.map((q, index) => ({
      questionId: q.id,
      questionText: q.text,
      answer:
        `This is a demo draft answer for question ${index + 1}. ` +
        `When the CrewAI backend is connected, this will be evidence-bound and generated by the 4-agent pipeline.`,
      status: "draft",
      citations: [
        {
          document: "Information Security Policy v2.3",
          section: "Section 4.1 — Access Control Policy",
          snippet:
            "All access to systems and data is governed by least privilege. Access is reviewed quarterly."
        }
      ]
    }));

    console.warn(
      isAbort
        ? `startRun timed out after ${START_RUN_TIMEOUT_MS}ms; using demo results.`
        : "startRun failed; using demo results.",
      err
    );

    return { runId, results };
  } finally {
    window.clearTimeout(timeout);
  }
}

export async function buildRagIndex(params?: {
  path?: string;
  max_files?: number;
  chunk_size?: number;
  chunk_overlap?: number;
}): Promise<RAGBuildResponse> {
  let response: Response;
  try {
    response = await fetch(apiUrl("/api/rag/build"), {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        path: params?.path ?? null,
        max_files: params?.max_files ?? null,
        chunk_size: params?.chunk_size ?? 1200,
        chunk_overlap: params?.chunk_overlap ?? 150
      })
    });
  } catch (err) {
    // Browser-level network error (backend down, wrong URL, blocked, etc.)
    const target = apiUrl("/api/rag/build");
    const hint = API_BASE_URL
      ? `Check VITE_BACKEND_URL=${API_BASE_URL}`
      : "Start the backend on http://127.0.0.1:8000 (or set VITE_BACKEND_URL).";
    throw new Error(
      `Failed to reach backend at ${target}. ${hint}`
    );
  }

  if (!response.ok) {
    const message = await safeReadErrorMessage(response);
    throw new Error(
      message ?? `Failed to build RAG index (status ${response.status}).`
    );
  }

  return (await response.json()) as RAGBuildResponse;
}

async function safeReadErrorMessage(
  response: Response
): Promise<string | null> {
  try {
    const data = (await response.json()) as { detail?: string };
    if (typeof data.detail === "string") {
      return data.detail;
    }
  } catch {
    // ignore
  }
  return null;
}

export async function getRunStatus(
  runId: string
): Promise<GetRunStatusResponse> {
  console.debug("getRunStatus called with runId:", runId);

  // For MVP1 we treat the run as synchronous: once /api/run returns,
  // the results are already available. This function remains a stub
  // for potential future polling support.
  return {
    status: "completed"
  };
}

